//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_Receives
    {
        public OA_Receives()
        {
            this.OA_Reads = new HashSet<OA_Reads>();
            this.OA_Signatures = new HashSet<OA_Signatures>();
        }
    
        public int ID { get; set; }
        public string OfficeSerial { get; set; }
        public string SerialNumber { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public string Emergency { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Staff_ID { get; set; }
        public Nullable<System.DateTime> GetDate { get; set; }
        public string KeyWords { get; set; }
        public Nullable<System.DateTime> PostilDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string DealType { get; set; }
        public string MainDept { get; set; }
        public string Abstract { get; set; }
        public string PrimaryAttitude { get; set; }
        public Nullable<int> PrimaryDept_ID { get; set; }
        public Nullable<int> PrimaryStaff_ID { get; set; }
        public Nullable<System.DateTime> PrimaryDate { get; set; }
        public string DealAttitude { get; set; }
        public Nullable<int> DealDept_ID { get; set; }
        public Nullable<int> DealStaff_ID { get; set; }
        public Nullable<System.DateTime> DealDate { get; set; }
        public string ResultAttitude { get; set; }
        public Nullable<int> ResultDept_ID { get; set; }
        public Nullable<int> ResultStaff_ID { get; set; }
        public Nullable<System.DateTime> ResultDate { get; set; }
        public Nullable<bool> IsArchives { get; set; }
        public byte[] RowVersion { get; set; }
        public string OldSystemId { get; set; }
        public string LeaderAttitude { get; set; }
        public Nullable<int> LeaderDept_ID { get; set; }
        public Nullable<int> Leader_ID { get; set; }
        public Nullable<System.DateTime> LeaderDate { get; set; }
        public string PrimaryAttitudeCheck { get; set; }
        public Nullable<int> PrimaryCheckDept_ID { get; set; }
        public Nullable<int> PrimaryCheckStaff_ID { get; set; }
        public Nullable<System.DateTime> PrimaryDateCheck { get; set; }
        public string PrimaryAttitudeExamine { get; set; }
        public Nullable<int> PrimaryExamineDept_ID { get; set; }
        public Nullable<int> PrimaryExamineStaff_ID { get; set; }
        public Nullable<System.DateTime> PrimaryDateExamine { get; set; }
        public string CommitValue { get; set; }
        public Nullable<bool> IsHasten { get; set; }
    
        public virtual ICollection<OA_Reads> OA_Reads { get; set; }
        public virtual OG_Depts OG_Depts { get; set; }
        public virtual OG_Depts OG_Depts1 { get; set; }
        public virtual OG_Depts OG_Depts2 { get; set; }
        public virtual OG_Depts OG_Depts3 { get; set; }
        public virtual OG_Depts OG_Depts4 { get; set; }
        public virtual OG_Depts OG_Depts5 { get; set; }
        public virtual OG_Staffs OG_Staffs { get; set; }
        public virtual OG_Staffs OG_Staffs1 { get; set; }
        public virtual OG_Staffs OG_Staffs2 { get; set; }
        public virtual OG_Staffs OG_Staffs3 { get; set; }
        public virtual OG_Staffs OG_Staffs4 { get; set; }
        public virtual OG_Staffs OG_Staffs5 { get; set; }
        public virtual OG_Staffs OG_Staffs6 { get; set; }
        public virtual S_Projects S_Projects { get; set; }
        public virtual ICollection<OA_Signatures> OA_Signatures { get; set; }
    }
}
