//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OA_Sends
    {
        public int ID { get; set; }
        public string OfficeSerial { get; set; }
        public string SerialNumber { get; set; }
        public string Title { get; set; }
        public string Type { get; set; }
        public Nullable<bool> IsOpen { get; set; }
        public string Secret { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public string AttituderName { get; set; }
        public Nullable<System.DateTime> PrintDate { get; set; }
        public string KeyWords { get; set; }
        public string CopyDepartment { get; set; }
        public string CopyNotice { get; set; }
        public string Attitude { get; set; }
        public Nullable<int> PrintCount { get; set; }
        public string LeaderAttitude { get; set; }
        public string LeaderStaffName { get; set; }
        public Nullable<System.DateTime> LeaderStaffDate { get; set; }
        public string SignAttitude { get; set; }
        public Nullable<int> Staff_ID { get; set; }
        public Nullable<int> StaffDept_ID { get; set; }
        public string CheckStaffName { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> IsArchives { get; set; }
        public byte[] RowVersion { get; set; }
        public string OldSystemId { get; set; }
        public Nullable<int> TemplateType_ID { get; set; }
        public string DeptAttitude { get; set; }
        public string DeptStaffName { get; set; }
        public Nullable<System.DateTime> DeptStaffDate { get; set; }
        public string CollateStaffName { get; set; }
        public string PrintStaffName { get; set; }
        public string SealStaffName { get; set; }
        public string ScanStaffName { get; set; }
        public string AuditorStaffName { get; set; }
        public string CheckAttitude { get; set; }
        public Nullable<System.DateTime> CheckDate { get; set; }
        public string AuditorAttitude { get; set; }
        public Nullable<System.DateTime> AuditorDate { get; set; }
        public Nullable<int> RetractPrintCount { get; set; }
        public string RetractDescription { get; set; }
        public Nullable<int> RetractStaffId { get; set; }
        public Nullable<System.DateTime> RetractDate { get; set; }
        public string RetractDeptAttitude { get; set; }
        public string RetractDeptLeader { get; set; }
        public Nullable<System.DateTime> RetractDeptLeaderDate { get; set; }
        public string RetractAttitude { get; set; }
        public string RetractAttitudeName { get; set; }
        public Nullable<System.DateTime> RetractAttitudeDate { get; set; }
        public string RetractRemark { get; set; }
        public Nullable<System.DateTime> CollateDate { get; set; }
        public string DeptCheckAttitude { get; set; }
        public string DeptCheckStaffName { get; set; }
        public Nullable<System.DateTime> DeptCheckStaffDate { get; set; }
        public string Public { get; set; }
    
        public virtual OG_Depts Dept { get; set; }
        public virtual OG_Staffs RetractStaff { get; set; }
        public virtual OG_Staffs Staff { get; set; }
        public virtual S_Projects S_Projects { get; set; }
    }
}
