//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OG_Depts
    {
        public OG_Depts()
        {
            this.OA_Cooperates = new HashSet<OA_Cooperates>();
            this.OA_Reads = new HashSet<OA_Reads>();
            this.OA_Receives = new HashSet<OA_Receives>();
            this.OA_Receives1 = new HashSet<OA_Receives>();
            this.OA_Receives2 = new HashSet<OA_Receives>();
            this.OA_Receives3 = new HashSet<OA_Receives>();
            this.OA_Receives4 = new HashSet<OA_Receives>();
            this.OA_Receives5 = new HashSet<OA_Receives>();
            this.OA_Sends = new HashSet<OA_Sends>();
            this.OG_Depts1 = new HashSet<OG_Depts>();
            this.OG_DeptStaffs = new HashSet<OG_DeptStaffs>();
            this.S_ExpandValues = new HashSet<S_ExpandValues>();
            this.S_Processes = new HashSet<S_Processes>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public Nullable<int> Order { get; set; }
        public bool IsMain { get; set; }
        public string HomePage { get; set; }
        public int RootId { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public bool IsSubMain { get; set; }
        public bool IsLeader { get; set; }
    
        public virtual ICollection<OA_Cooperates> OA_Cooperates { get; set; }
        public virtual ICollection<OA_Reads> OA_Reads { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives1 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives2 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives3 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives4 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives5 { get; set; }
        public virtual ICollection<OA_Sends> OA_Sends { get; set; }
        public virtual ICollection<OG_Depts> OG_Depts1 { get; set; }
        public virtual OG_Depts OG_Depts2 { get; set; }
        public virtual OG_Usrs OG_Usrs { get; set; }
        public virtual ICollection<OG_DeptStaffs> OG_DeptStaffs { get; set; }
        public virtual ICollection<S_ExpandValues> S_ExpandValues { get; set; }
        public virtual ICollection<S_Processes> S_Processes { get; set; }
    }
}
