//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OG_RoleStaffs
    {
        public int ID { get; set; }
        public short Order { get; set; }
        public int Role_ID { get; set; }
        public int Staff_ID { get; set; }
    
        public virtual OG_Roles OG_Roles { get; set; }
        public virtual OG_Staffs OG_Staffs { get; set; }
    }
}
