//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OG_Roles
    {
        public OG_Roles()
        {
            this.OG_Roles1 = new HashSet<OG_Roles>();
            this.OG_RoleStaffs = new HashSet<OG_RoleStaffs>();
        }
    
        public int ID { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Parent_ID { get; set; }
        public bool IsShare { get; set; }
    
        public virtual ICollection<OG_Roles> OG_Roles1 { get; set; }
        public virtual OG_Roles OG_Roles2 { get; set; }
        public virtual OG_Usrs OG_Usrs { get; set; }
        public virtual ICollection<OG_RoleStaffs> OG_RoleStaffs { get; set; }
    }
}
