//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class OG_Staffs
    {
        public OG_Staffs()
        {
            this.OA_Cooperates = new HashSet<OA_Cooperates>();
            this.OA_Reads = new HashSet<OA_Reads>();
            this.OA_Receives = new HashSet<OA_Receives>();
            this.OA_Receives1 = new HashSet<OA_Receives>();
            this.OA_Receives2 = new HashSet<OA_Receives>();
            this.OA_Receives3 = new HashSet<OA_Receives>();
            this.OA_Receives4 = new HashSet<OA_Receives>();
            this.OA_Receives5 = new HashSet<OA_Receives>();
            this.OA_Receives6 = new HashSet<OA_Receives>();
            this.OA_Sends = new HashSet<OA_Sends>();
            this.OA_Sends1 = new HashSet<OA_Sends>();
            this.OG_DeptStaffs = new HashSet<OG_DeptStaffs>();
            this.OG_RoleStaffs = new HashSet<OG_RoleStaffs>();
            this.OA_Signatures = new HashSet<OA_Signatures>();
            this.S_ExpandValues = new HashSet<S_ExpandValues>();
            this.S_Processes = new HashSet<S_Processes>();
            this.S_Processes1 = new HashSet<S_Processes>();
            this.S_ProjectItems = new HashSet<S_ProjectItems>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Order { get; set; }
        public string LogName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Mobile { get; set; }
        public string Sex { get; set; }
        public string Blood { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Address { get; set; }
        public string EMail { get; set; }
        public string Qualification { get; set; }
        public bool HideMap { get; set; }
        public bool HideSearch { get; set; }
        public string Duty { get; set; }
        public string PicName { get; set; }
        public bool IsPermiss { get; set; }
        public bool IsMaster { get; set; }
        public bool IsSubMaster { get; set; }
        public bool IsMultiSign { get; set; }
    
        public virtual ICollection<OA_Cooperates> OA_Cooperates { get; set; }
        public virtual ICollection<OA_Reads> OA_Reads { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives1 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives2 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives3 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives4 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives5 { get; set; }
        public virtual ICollection<OA_Receives> OA_Receives6 { get; set; }
        public virtual ICollection<OA_Sends> OA_Sends { get; set; }
        public virtual ICollection<OA_Sends> OA_Sends1 { get; set; }
        public virtual ICollection<OG_DeptStaffs> OG_DeptStaffs { get; set; }
        public virtual ICollection<OG_RoleStaffs> OG_RoleStaffs { get; set; }
        public virtual ICollection<OA_Signatures> OA_Signatures { get; set; }
        public virtual OG_Usrs OG_Usrs { get; set; }
        public virtual ICollection<S_ExpandValues> S_ExpandValues { get; set; }
        public virtual ICollection<S_Processes> S_Processes { get; set; }
        public virtual ICollection<S_Processes> S_Processes1 { get; set; }
        public virtual ICollection<S_ProjectItems> S_ProjectItems { get; set; }
    }
}
