//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_Annexs
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public string Name { get; set; }
        public string Extended { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string Path { get; set; }
        public Nullable<int> Order { get; set; }
        public string SystemType { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> S_Project_ID { get; set; }
        public Nullable<int> CreatorId { get; set; }
        public string MarkCode { get; set; }
        public int Size { get; set; }
        public string Url { get; set; }
        public string FKTable { get; set; }
        public Nullable<int> FKValue { get; set; }
        public bool HasRevision { get; set; }
    
        public virtual S_Projects S_Projects { get; set; }
    }
}
