//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GetOAInfomations.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class S_ProjectItems
    {
        public S_ProjectItems()
        {
            this.S_ProjectItems1 = new HashSet<S_ProjectItems>();
        }
    
        public int ID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> SignDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public int PrevStaffId { get; set; }
        public bool Finished { get; set; }
        public int StatusValue { get; set; }
        public string Remark { get; set; }
        public int CurStaffId { get; set; }
        public int CurActionId { get; set; }
        public int PrevActionId { get; set; }
        public Nullable<int> PrevItem_ID { get; set; }
        public int ProjectId { get; set; }
    
        public virtual OG_Staffs OG_Staffs { get; set; }
        public virtual OG_Usrs OG_Usrs { get; set; }
        public virtual ICollection<S_ProjectItems> S_ProjectItems1 { get; set; }
        public virtual S_ProjectItems S_ProjectItems2 { get; set; }
        public virtual S_Projects S_Projects { get; set; }
    }
}
